name: Package CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install flake8
        pip install mypy
        pip install coverage
    - name: Run Tests
      run: |
        pytest tests
      env:
        TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
    - name: Run flake8
      run: |
        flake8 pyteledantic

    - name: Run mypy
      run: |
        mypy pyteledantic
        
    - name: Run coverage
      run: |
        coverage run -m pytest tests
        
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
